-- Create MergeTree table
-- Create ReplacingMergeTree table
-- Create VersioningMergeTree table
-- Create SummingMergeTree table
-- Create EmbeddedRocksDB table
-- Create NULL table
-- Create Log table
-- Create S3 table